### ISSUE TITLE
DeFuzz

### ISSUE THREAD

**Issue by dedu6ka** [lovac42/DeFuzz#1]
Windows 8, Anki 2,0,52    
Download failed: Traceback (most recent call last):
  File "aqt\downloader.py", line 67, in run
  File "thirdparty\httplib2\__init__.py", line 1597, in request
  File "thirdparty\httplib2\__init__.py", line 1345, in _request
  File "aqt\sync.py", line 467, in _conn_request
  File "thirdparty\httplib2\__init__.py", line 1036, in connect
SSLHandshakeError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:661)  

With all the add-ons turned off, the download was ok.
Add-on itself works, too.
Question: should i identify the culprit ? Do you have an idea what add-on could be at fault ?

**Comment by lovac42** [comment]
Turn them off one by one and check.
