### ISSUE TITLE
Serious issue on Anki 2.1.24beta4

### ISSUE THREAD

**Issue by cjdduarte** [lovac42/DeFuzz#7]
Anki 2.1.24 (16ab351b) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-04-08 10:10:06

This causes an issue on 2.1.24beta4 that breaks the profile and you have to restore from backup when you try to access the options for a deck

```
Caught exception:
Traceback (most recent call last):
  File "aqt\deckbrowser.py", line 246, in <lambda>
  File "aqt\deckbrowser.py", line 275, in _options
  File "aqt\main.py", line 1009, in onDeckConf
  File "aqt\deckconf.py", line 36, in __init__
  File "aqt\deckconf.py", line 64, in setupConfs
  File "aqt\deckconf.py", line 81, in loadConfs
  File "aqt\deckconf.py", line 101, in onConfChange
  File "<D:\Anki\Anki.2.1.24b4\decorator.pyc:decorator-gen-22>", line 2, in saveConf
  File "lib\site-packages\anki\hooks.py", line 638, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 633, in repl
  File "<D:\Anki\Anki.2.1.24b4\decorator.pyc:decorator-gen-14>", line 2, in saveConf
  File "lib\site-packages\anki\hooks.py", line 638, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 633, in repl
  File "aqt\deckconf.py", line 317, in saveConf
  File "lib\site-packages\anki\decks.py", line 77, in save
  File "lib\site-packages\anki\decks.py", line 342, in update_config
  File "lib\site-packages\anki\rsbackend.py", line 516, in add_or_update_deck_config
orjson.JSONEncodeError: Type is not JSON serializable: CheckState
```

**Comment by lovac42** [comment]
Thanks for letting me know. Why do you need to restore from backup? It's just typecasting issue as the qt checkbox can't be converted into a a JSON value due to the change to Rust.

The same applies for freeweekend. Adding int() or str() will fix it.
```
checkbox = int(self.conf.mycheckbox.checkState())
```

This should be a problem with anki's rsbackend code not auto converting the values.
